### ISSUE TITLE
Fails to build on Ubuntu 12.04 with "undefined reference to `clock_gettime'"

### ISSUE THREAD

**Issue by hotice** [majn/telegram-purple#21]
telegram-purple fails to build under Ubuntu 12.04 (both 32bit and 64bit) with the following error:

```
gcc  -g -O2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple   -Wall -Wextra -Wno-unused-parameter -I. -I. -fno-strict-aliasing -fPIC -I/usr/include -I/usr/include -DFLAGS -iquote ./tgl -c -MP -MD -MF dep/tools.d -MQ objs/tools.o -o objs/tools.o tgl/tools.c
gcc objs/generate.o objs/tools.o -L/usr/lib -L/usr/lib   -lpurple -lglib-2.0   -lz -lm  -lcrypto -rdynamic -ggdb -o bin/generate
objs/tools.o: In function `tgl_my_clock_gettime':
/home/andrei/telegram-purple-0.5/tgl/tools.c:261: undefined reference to `clock_gettime'
```

Compiling tgl separately works, so this is caused by telegram-purple.
