### ISSUE TITLE
Fails to build on 32bit

### ISSUE THREAD

**Issue by hotice** [majn/telegram-purple#20]
telegram-purple (both the latest Git and v0.5) fails to build tl-parser on Ubuntu 32bit (tested on Ubuntu 14.04 and 14.10), with the following error:

```
make[1]: Entering directory '/build/buildd/telegram-purple-0.5'
cat tgl/scheme.tl tgl/encrypted_scheme.tl tgl/binlog.tl tgl/append.tl > auto/scheme.tl
gcc  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -Wall -Wextra -Wno-unused-parameter -I. -I. -fno-strict-aliasing -fPIC -m64 -D_FORTIFY_SOURCE=2 -I/usr/include -I/usr/include -DFLAGS -iquote ./tgl/tl-parser -c -MP -MD -MF dep/tl-parser.d -MQ objs/tl-parser.o -o objs/tl-parser.o tgl/tl-parser/tl-parser.c
In file included from /usr/include/unistd.h:25:0,
                 from tgl/tl-parser/tl-parser.c:28:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile.tl-parser:5: recipe for target 'objs/tl-parser.o' failed
make[1]: *** [objs/tl-parser.o] Error 1
make[1]: Leaving directory '/build/buildd/telegram-purple-0.5'
dh_auto_build: make -j1 returned exit code 2
```

When compiled separately, tgl and tl-parser can be compiled successfully, but not via telegram-purple.
